# Generated by Django 5.0.1 on 2025-04-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0002_blog_contactinfo_faq_homepagebanner_safetytip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopTrek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='toptreks/')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='whatsnew/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('booking', 'Booking & Payment'), ('treks', 'Treks & Activities'), ('safety', 'Safety & Equipment'), ('Cancellation & Refund', 'Cancellation & Refund'), ('Payment-Related', 'Payment-Related'), ('Customer-support', 'Customer-Support')], default='general', max_length=50),
        ),
    ]
