# Generated by Django 5.0.1 on 2025-04-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0003_toptrek_whatsnew_alter_faq_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsnew',
            old_name='date_posted',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='toptrek',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='toptrek',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
