# Generated by Django 5.2.3 on 2025-08-20 05:05

import ckeditor.fields
import treks_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0004_rename_date_posted_whatsnew_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='toptrek',
            name='image_url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='whatsnew',
            name='image_url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/', validators=[treks_app.models.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='homepagebanner',
            name='image',
            field=models.ImageField(upload_to='banners/', validators=[treks_app.models.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='safetytip',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='safety_icons/', validators=[treks_app.models.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/', validators=[treks_app.models.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(upload_to='team/', validators=[treks_app.models.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', validators=[treks_app.models.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='toptrek',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='toptreks/'),
        ),
        migrations.AlterField(
            model_name='trek',
            name='image',
            field=models.ImageField(upload_to='treks/', validators=[treks_app.models.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='trekimage',
            name='image',
            field=models.ImageField(upload_to='trek_images/', validators=[treks_app.models.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='trekorganizer',
            name='logo',
            field=models.ImageField(upload_to='organizers/', validators=[treks_app.models.validate_image_file_extension]),
        ),
    ]
