# Generated by Django 5.2.3 on 2025-09-10 07:07

import ckeditor.fields
import treks_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0005_blog_image_url_toptrek_image_url_whatsnew_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms and Conditions', max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='toptrek',
            name='location',
        ),
        migrations.AddField(
            model_name='blog',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/originals/', validators=[treks_app.models.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='blog',
            name='original_image_url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['visit_time'], name='treks_app_v_visit_t_fdf07d_idx'), models.Index(fields=['ip_address'], name='treks_app_v_ip_addr_982555_idx')],
            },
        ),
    ]
