# Generated by Django 5.2.3 on 2025-09-04 07:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0006_remove_toptrek_location_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms and Conditions', max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
