# Generated by Django 5.2.3 on 2025-09-04 07:47

import treks_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0007_termsandconditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/originals/', validators=[treks_app.models.validate_image_file_extension]),
        ),
    ]
