# Generated by Django 5.2.3 on 2025-09-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0008_blog_original_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='original_image_url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
